plugins {
    id 'architectury-plugin'
}

architectury {
    common(rootProject.ext.supportedPlatforms)
}

loom {
    accessWidenerPath = file('src/main/resources/arclight.accesswidener')
}

dependencies {
    modImplementation libs.fabric.loader

    compileOnly rootProject.ext.generatedSpigot

    implementation libs.izzel.tools
    implementation libs.arclight.api
    implementation libs.mixin.tools
    annotationProcessor(libs.mixin.tools) { transitive = false }

    // spigot
    implementation libs.spigot.api
    implementation libs.jline
    implementation libs.terminalconsoleappender
    implementation libs.specialsource
    implementation libs.log4j.jul
    implementation libs.bungeecord.chat
    implementation libs.mysql.connectorj
    implementation libs.snakeyaml
    implementation(libs.bundles.adventure) {
        exclude group: 'org.slf4j'
        exclude group: 'org.checkerframework'
    }

    implementation project(':i18n-config')
    testImplementation platform('org.junit:junit-bom:5.14.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

compileJava {
    options.compilerArgs << '-XDignore.symbol.file' << '-XDenableSunApiLintControl'
    options.encoding = 'UTF-8'
}
