plugins {
    id 'luminara.java-conventions'
}

base.archivesName = 'luminara-i18n-config'


dependencies {
    implementation "org.spongepowered:configurate-yaml:${libs.versions.configurate.get()}"
    implementation "org.apache.logging.log4j:log4j-api:${libs.versions.log4j.get()}"
    implementation "org.apache.logging.log4j:log4j-core:${libs.versions.log4j.get()}"
}
